### ISSUE TITLE
Failed to load the line-ending-selector package

### ISSUE THREAD

**Issue by velechva** [atom/line-ending-selector#16]
[Enter steps to reproduce below:]
1. Start Atom with the line-end-selector plugin enable
   or
2. Enable the line-end-selector plugin in settings

**Atom Version**: 1.2.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Failed to load the line-ending-selector package

```
At Unexpected token ILLEGAL

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\line-ending-selector\lib\main.js:16:22)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package.js:661:34)
    at C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\src\package-manager.js:160:19)
    at HTMLButtonElement.<anonymous> (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Vic\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
     -7:06.6.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -6:53.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:48.6.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -6:41 core:backspace (atom-text-editor.editor.is-focused)
     -6:30.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:26.1.0 core:save-as (atom-text-editor.editor.is-focused)
     -6:21.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:21.9.0 core:cut (atom-text-editor.editor.is-focused)
  2x -3:19.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:18.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:16.7.0 core:cut (atom-text-editor.editor.is-focused)
     -3:15.7.0 core:paste (atom-text-editor.editor.is-focused)
  3x -3:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:12 core:save (atom-text-editor.editor.is-focused)
     -0:38.2.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by damieng** [comment]
No new reports of this in 10 months, closing.
