### ISSUE TITLE
Failed to load the line-ending-selector package(EPERM: operation not permitted, write)

### ISSUE THREAD

**Issue by LendLord** [atom/line-ending-selector#18]
[Enter steps to reproduce below:]
1. Install atom
2. Error occured

**Atom Version**: 1.4.0-beta0
**System**: Unknown Windows Version
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Failed to load the line-ending-selector package

```
At C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write

Error: C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Function.log (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
    at enabled (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
    at Logger.debug (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
    at File.parse (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
    at File.parseCode (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
    at File.wrap (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
    at Pipeline.transform (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:165:17)
    at Object.exports.compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\babel.js:51:16)
    at compileFileAtPath (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:72:44)
    at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:203:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\line-ending-selector\lib\main.js:16:22)
    at Module._compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:721:27)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:443:14)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "achievements",
      "save-session",
      "docblockr",
      "whitespace",
      "atom-ternjs",
      "minimap-highlight-selected",
      "minimap-pigments",
      "minimap-selection",
      "minimap-split-diff",
      "linter",
      "linter-htmlhint",
      "linter-jshint",
      "linter-php"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
atom-alignment, v0.12.1
atom-beautify, vundefined
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
color-picker, v2.0.14
file-icons, v1.6.13
highlight-selected, v0.11.1
indent-guide-improved, v1.4.5
minimap, v4.18.0
pigments, v0.19.3
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tool-bar-main, v0.0.8
trailing-spaces, v0.3.2
tree-view-open-files, v0.3.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
I believe this was fixed by https://github.com/atom/atom/pull/10395.
