### ISSUE TITLE
Uncaught TypeError: _statusBarItem2.default is not a function

### ISSUE THREAD

**Issue by genereese** [atom/line-ending-selector#19]
[Enter steps to reproduce below:]
1. Opened an HTML file

**Atom Version**: 1.3.2
**System**: "Fedora release
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-django",
      "turbo-javascript"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-django, v0.3.2
color-picker, v2.0.13
css-snippets, v0.9.0
django-templates, v0.5.0
javascript-snippets, v1.0.0
minimap, v4.18.4
rulerz, v0.4.1
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by damieng** [comment]
Going to track this as part of https://github.com/atom/line-ending-selector/issues/19 as it has newer call stack/semantics.
