### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by 1j01** [atom/line-ending-selector#2]
[Enter steps to reproduce below:]
1. Try to convert line endings (CRLF to LF)

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Home
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.0.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Isaiah\.atom\packages\line-ending-selector\lib\main.js:158

TypeError: undefined is not a function
  at setLineEnding (C:\Users\Isaiah\.atom\packages\line-ending-selector\lib\main.js:158:12)
  at LineEndingListView.callback (C:\Users\Isaiah\.atom\packages\line-ending-selector\lib\main.js:91:7)
  at LineEndingListView.confirmed (C:\Users\Isaiah\.atom\packages\line-ending-selector\lib\line-ending-list-view.js:54:12)
  at LineEndingListView.module.exports.SelectListView.confirmSelection (C:\Users\Isaiah\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at HTMLLIElement.<anonymous> (C:\Users\Isaiah\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\Isaiah\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\Users\Isaiah\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -6:15.4.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-min-ui.find-visible)
     -6:01.7.0 window:toggle-dev-tools (div.settings-view.pane-item)
     -4:38.6.0 core:cancel (div.settings-view.pane-item)
     -4:37.3.0 window:toggle-dev-tools (div.settings-view.pane-item)
     -4:20.3.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-min-ui)
     -4:11.4.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -4:03.7.0 core:close (select.form-control)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autoflow",
      "themed-settings",
      "save-session",
      "log-console",
      "tabs",
      "language-autohotkey"
    ],
    "autoHideMenuBar": true,
    "projectHome": "C:\\Users\\Isaiah\\!!Projects\\",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-live-grammar-reload, v0.3.0
autoclose-html, v0.18.0
line-ending-selector, v0.0.2
minimap, v4.12.3
minimap-find-and-replace, v4.2.1
minimap-git-diff, v4.1.7
seti-syntax, v0.4.0
seti-ui, v0.8.0
space-tab, v0.4.2

# Dev
No dev packages
```

**Comment by ghost** [comment]
+1
1. Open new window with blank document

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.0.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\tom\.atom\packages\line-ending-selector\lib\main.js:81

TypeError: undefined is not a function
  at updateTile (C:\Users\tom\.atom\packages\line-ending-selector\lib\main.js:81:14)
  at C:\Users\tom\.atom\packages\line-ending-selector\lib\main.js:95:9
  at C:\Users\tom\.atom\packages\line-ending-selector\lib\main.js:112:9
  at Emitter.module.exports.Emitter.emit (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:306:21)
  at tabs-tab.<anonymous> (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\tom\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -4:22 core:delete (atom-text-editor.editor.is-focused)
 11x -4:20.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:18.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -4:17.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:16.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:15.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -4:15 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -4:14.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:13.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:06.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:06.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:05.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:05.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:03.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:01.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:31.5.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
emmet, v2.3.12
hidpi, v0.7.0
line-ending-converter, v1.3.2
line-ending-selector, v0.0.3
linter, v1.4.3
linter-scss-lint, v2.0.0
minimap, v4.12.3
pigments, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
cc @jlord @maxbrunsfeld for :eyes:

**Comment by MrMic** [comment]
Same issue but with Mac OSX Yosemite.

**Comment by jlord** [comment]
@MrMic in which situation are you getting the error? The two here are different, one is after converting a file to a new line ending and one is after opening a new blank file in a new window.

**Comment by MrMic** [comment]
after opening a new blank file in a new tab.

**Comment by maxbrunsfeld** [comment]
@1j01 @MrMic @tomodwyer I'm sorry, this package depends on new features in Atom core that have not been released yet, so it doesn't work against the current version of Atom. I should have made that more clear for the time being.

We now intend to actually bundle this package with the next release of Atom, v1.0.8. I will post a comment here when 1.0.8 ships so that you can upgrade Atom. In the meantime, please uninstall this package. :disappointed:

**Comment by ghost** [comment]
Thanks for the update. I clean installed Atom today on a new system and spotted this package - can't wait to get it working in the next version.

Keep up the good work :thumbsup:

**Comment by 1j01** [comment]
1.0.8 shipped
