### ISSUE TITLE
Failed to activate the line-ending-selector package

### ISSUE THREAD

**Issue by JerryFZhang** [atom/line-ending-selector#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Failed to activate the line-ending-selector package

```
At ENOENT: no such file or directory, lstat '/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz'

Error: ENOENT: no such file or directory, lstat '/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryExtensions (module.js:115:20)
    at Function.Module._findPath (module.js:166:18)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/transformers/es6/parameters/default.js:24:14)
    at Module._compile (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/transformers/es6/parameters/index.js:12:16)
    at Module._compile (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/transformers/index.js:63:21)
    at Module._compile (/Users/jerryzhang/Library/Application Support/com.github.atom.ShipIt/update.iLAd4dz/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-light-ui",
      "native-ui"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by damieng** [comment]
No additional reports of this for 6 months, closing.

**Comment by AbsoluteBreeze** [comment]
[Enter steps to reproduce:]

1. ... Upon opening Atom

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package 0.5.1


### Stack Trace

Failed to activate the line-ending-selector package

```
At UNKNOWN: unknown error, open 'C:\Users\tr2000\.atom\compile-cache\js\babel\ce35514db6341e7f32f611892410fdea5abbc019\3b0d29dd39429f1900408efbc9ff732d2bfb80b6.js'

Error: UNKNOWN: unknown error, open 'C:\Users\tr2000\.atom\compile-cache\js\babel\ce35514db6341e7f32f611892410fdea5abbc019\3b0d29dd39429f1900408efbc9ff732d2bfb80b6.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at writeCachedJavascript (/app.asar/src/compile-cache.js:111:6)
    at compileFileAtPath (/app.asar/src/compile-cache.js:92:7)
    at /app.asar/src/compile-cache.js:215:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/line-ending-selector/lib/main.js:16:22)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
```

### Commands

```
     -0:38.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
file-icons 2.0.16 
fold-functions 0.5.0 
pigments 0.39.0 
```
