### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by d5dhatch** [atom/line-ending-selector#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package 0.6.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:362

RangeError: Maximum call stack size exceeded
    at Object.spliceWithArray (/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:362:46)
    at TokenizedBuffer.module.exports.TokenizedBuffer.bufferDidChange (/app.asar/src/tokenized-buffer.js:278:18)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:670:36
    at Set.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:669:33)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:663:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:16)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:821:14)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:535:21)
    at TextBuffer.module.exports.TextBuffer.setText (/app.asar/node_modules/text-buffer/lib/text-buffer.js:475:19)
    at setLineEnding (/app.asar/node_modules/line-ending-selector/lib/main.js:173:12)
    at Object.didConfirmSelection (/app.asar/node_modules/line-ending-selector/lib/main.js:48:13)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at SelectListView.didClickItem (/app.asar/node_modules/atom-select-list/src/select-list-view.js:220:10)
    at ListItemView.onclick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:156:33)
    at ListItemView.didClick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:349:10)
```

### Commands

```
     -6:24.8.0 application:add-project-folder (input.hidden-input)
     -6:01.9.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:43 project-manager:save-project (input.hidden-input)
     -5:16.2.0 project-manager:list-projects (input.hidden-input)
     -3:08.1.0 project-manager:save-project (input.hidden-input)
     -2:56.4.0 project-manager:list-projects (input.hidden-input)
     -2:38.5.0 project-manager:update-projects (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gedcom-theme-syntax.theme-one-dark-ui)
     -2:32.6.0 project-manager:save-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gedcom-theme-syntax.theme-one-dark-ui)
  3x -2:00.5.0 project-manager:list-projects (input.input-text)
     -0:33.4.0 command-palette:toggle (input.hidden-input)
     -0:27.6.0 line-ending-selector:convert-to-LF (input.hidden-input)
     -0:10.7.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-css-class-checker 0.4.3 
atom-terminal-panel 4.4.4 
atomizr 0.23.1 
aurora-theme 1.2.2 
color-tabs 0.1.8 
command-executor 1.4.3 
compare-files 0.8.0 
cson 2.0.1 
css-edit-groups 0.4.2 
file-type-icons 1.3.3 
file-type-icons 1.3.3 
foldername-tabs 0.2.4 
language-gedcom 1.1.1 
gedcom-theme-syntax 1.0.3 
git-time-machine 1.5.9 
grammar-live-reload 1.0.5 
grammar-tab-colors 0.2.8 
language-SCSS 0.4.0 
language-sml 0.7.0 
nord-atom-syntax 0.7.0 
nord-atom-ui 0.11.0 
open-in-browser 0.5.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-dir 0.0.17 
project-manager 3.3.4 
quick-editor 0.4.3 
regex-filter-and-generator 1.4.2 
remove-whitespace 0.2.1 
restart-atom 0.2.0 
Sass-Syntax-Highlight 0.1.1 
ScssBundle 0.5.0 
set-syntax 0.3.2 
TreeColor 1.0.6 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
