### ISSUE TITLE
Uncaught SyntaxError:  Invalid or unexpected token

### ISSUE THREAD

**Issue by myhubspot** [atom/line-ending-selector#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.34.2

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\opera\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:82

SyntaxError: Invalid or unexpected token
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/autocomplete-plus/lib/provider-manager.js:13:20)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:29:24)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.getAutocompleteManager (/app.asar/node_modules/autocomplete-plus/lib/main.js:47:33)
    at /app.asar/node_modules/autocomplete-plus/lib/main.js:37:23)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.3 
atom-material-ui 1.3.9 
nord-atom-ui 0.10.1 
Remote-FTP 0.10.5 
```

**Comment by damieng** [comment]
Please try running atom in safe mode - `atom --safe` and see if you still get the error.

**Comment by jasonrudolph** [comment]
Thank you for letting us know that you ran into this issue.

We haven't gotten a response to our suggestion in https://github.com/atom/line-ending-selector/issues/44#issuecomment-295331745. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this issue, but don't hesitate to reach out if you're still experiencing this problem.
