### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by munhozfontana** [atom/line-ending-selector#49]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package 0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At C:\Users\munhoz\AppData\Local\atom\app-1.18.0\resources\app\src\command-registry.js:249

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:249:32)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at HTMLAnchorElement.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/line-ending-selector/lib/main.js:177:25)
```

### Commands

```
     -2:11.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:06.1.0 core:confirm (input.hidden-input)
     -2:04.2.0 intentions:highlight (input.hidden-input)
     -2:03.9.0 core:save (input.hidden-input)
     -2:00.8.0 intentions:highlight (input.hidden-input)
  2x -2:00.6.0 core:save (input.hidden-input)
     -1:58.7.0 intentions:highlight (input.hidden-input)
     -1:58 core:backspace (input.hidden-input)
     -1:57.1.0 intentions:highlight (input.hidden-input)
     -1:57 core:save (input.hidden-input)
  4x -1:55.5.0 core:backspace (input.hidden-input)
     -1:54.3.0 intentions:highlight (input.hidden-input)
  2x -1:54.2.0 core:save (input.hidden-input)
     -1:26.2.0 tree-view:copy (span.name.icon.icon-file-text)
     -1:25 tree-view:remove (div.tool-panel.tree-view)
  3x -2:13.3.0 line-ending-selector:show (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.6 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
