### ISSUE TITLE
Uncaught TypeError: _helpers2.default.getProcessPlatform is not a function

### ISSUE THREAD

**Issue by jbbae** [atom/line-ending-selector#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Home
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.0.5
### Stack Trace

Uncaught TypeError: _helpers2.default.getProcessPlatform is not a function

```
At C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:134

TypeError: _helpers2.default.getProcessPlatform is not a function
  at getPlatformLineEnding (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:134:28)
  at updateTile (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:80:32)
  at C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:95:9
  at C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:112:9
  at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane-container.js:140:7)
  at Workspace.module.exports.Workspace.observeActivePaneItem (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:294:33)
  at Object.consumeStatusBar (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\line-ending-selector\lib\main.js:89:34)
  at Provider.module.exports.Provider.provide (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
  at C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.11
language-babel, v0.15.0
minimap, v4.13.3
react-snippets, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
cc @maxbrunsfeld for :eyes:

**Comment by damieng** [comment]
Haven't seen any additional reports of this for a year, closing.
